services:
  angular-app:
    build:
      context: .
      dockerfile: angular-app.dockerfile
    ports:
      - "4200:4200"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

    command: ng serve --host 0.0.0.0 --port 4200
