version: "3.8"
services:
  angular-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - .:/app
      - /app/node_modules # Ignora node_modules do host
    environment:
      - CHOKIDAR_USEPOLLING=true # Necessário para live reload no Docker
